### PR TITLE
change math.h to cmath

### PR DESCRIPTION
**Pull request by tru7**
Signed-off-by: Othmar Truniger <github@truniger.ch>

fix src/suncalc.cpp

### CODE REVIEW

**Comment by tru7** [comment]
@2franix or @energy01 : do you still follow this repo?

**Comment by 2franix** [comment]
I do :) I'll review your PR shortly.

**Comment by tru7** [comment]
Thanks. Do you have a plan for release 0.0.1.34?

**Comment by 2franix** [comment]
Since there is a build issue with stretch, I think your fix deserves a version bump. I would say 0.0.1.34 should be created when warnings are addressed.

**Pull request merged**
